server:
  port: 3001
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/backend
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 10MB
